name: Development workflow - Testing and deployment
on: 
  push:
    branches:
      - development

jobs:
  frontend_tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Frontend tests here"
 
  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Backend tests here"

  frontend_deploy:
    runs-on: ubuntu-latest
      steps:
        - run: echo "Frontend deploy configs here"

  backend_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Backend deploy configs here"

  database_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Database stuff here (if needed)"
